_core:
  default_config_hash: 7R74wb0NllX6DTTAV9sfg790XV_QXshmF0wAobLEFNQ
langcode: es
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: horizontal
icon_default: true
icon_path: ''
high_contrast_mode: false
accent_color: ''
focus_color: ''
icon_upload: ''
show_user_theme_settings: true
css_enabled: 1
css: ".paragraph-type--cancion-item {\r\n  background-color: #f2f2ff;\r\n}\r\n.paragraphs-tabs-wrapper tr.paragraph-type--cancion-item:hover {\r\n  background-color: #f2f2ff;\r\n}"
plaintext_enabled: 0
autopreview_enabled: 0
preview_path: ''
