_core:
  default_config_hash: Ylohp6sdrL1dU4v-KcXzXTP-U8BAMgh4NWJA9eGHtO4
langcode: es
favicon:
  path: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: false
logo:
  path: ''
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: white
css_enabled: 1
css: ".cancion-item {\r\n  background-color: #f2f2ff;\r\n}"
plaintext_enabled: 0
autopreview_enabled: 0
preview_path: ''
