_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: es
uuid: 58709d5c-c5a8-47c4-91ae-96558c28f32a
name: LinajeSanto
mail: bloodlinenic@gmail.com
slogan: 'Somos Linaje Santo'
page:
  403: /user/login
  404: ''
  front: /proximo-evento
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: ''
